name: Internal Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Get short SHA
      id: short_sha
      run: echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT

    - name: set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Google Services JSON
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json
        echo "MD5 Checksum of google-services.json:"
        md5sum app/google-services.json

    - name: Build Release Bundle
      run: ./gradlew :app:bundleRelease --no-daemon

    - name: Sign AAB
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.RELEASE_SIGNING_KEY }}
        alias: ${{ secrets.RELEASE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

    - name: Upload to Google Play (Internal Testing)
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: dolphin.android.apps.schoolbell
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal
        status: completed

    - name: Send Discord Notification
      if: always()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        content: "SchoolBell Google Play Internal Publish"
        nodetail: true
        url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        description: "`${{ github.ref_name }}` | [${{ steps.short_sha.outputs.sha_short }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) by ${{ github.actor }}"
